import { missionSchema, missionTimelineEventSchema } from "@/lib/contracts/mission";

export const missionsMock = missionSchema.array().parse([
  {
    id: "mis-001",
    title: "Dashboard UI Framework",
    summary: "Create reusable dashboard cards and rows for the operator console.",
    description: "Build modular UI components for overview, missions, dispatches, QA, artifacts, and settings.",
    objective: "Give page layer a typed and reusable presentation toolkit.",
    status: "in_progress",
    priority: "high",
    owner: "Frontend Operator",
    lane: "UI",
    progress: 78,
    tags: ["dashboard", "ui", "typed-props"],
    blockers: [],
    dispatchCount: 5,
    completedDispatchCount: 4,
    artifactCount: 3,
    updatedAt: "2026-03-25 21:34",
    dueAt: "2026-03-26 09:00",
  },
  {
    id: "mis-002",
    title: "QA Gate Engine",
    summary: "Formalize QA decisions, evidence, and review outcomes.",
    description: "Support pending, approved, revision, blocked, failed, and force-approved outcomes.",
    objective: "Keep reviews auditable and easy to scan.",
    status: "qa_review",
    priority: "critical",
    owner: "QA Operator",
    lane: "Governance",
    progress: 62,
    tags: ["qa", "rules", "audits"],
    blockers: ["Need final evidence links from executor"],
    dispatchCount: 4,
    completedDispatchCount: 2,
    artifactCount: 2,
    updatedAt: "2026-03-25 21:21",
  },
  {
    id: "mis-003",
    title: "Seed Data & Docs Sync",
    summary: "Keep mock data and notes aligned with the live UI framework.",
    description: "Prepare pages for future real selectors while keeping development pleasant.",
    objective: "Reduce friction for the next integration pass.",
    status: "ready",
    priority: "medium",
    owner: "Integrator",
    lane: "Integration",
    progress: 18,
    tags: ["seed", "docs"],
    blockers: [],
    dispatchCount: 3,
    completedDispatchCount: 0,
    artifactCount: 1,
    updatedAt: "2026-03-25 20:55",
  },
  {
    id: "mis-004",
    title: "Mission State Engine",
    summary: "Provide transition rules and status selectors for missions.",
    description: "Implement a stable mission state machine that the dashboard can inspect safely.",
    objective: "Keep orchestration state predictable and reviewable.",
    status: "blocked",
    priority: "high",
    owner: "Systems Operator",
    lane: "State",
    progress: 46,
    tags: ["state", "transitions"],
    blockers: ["Waiting for final integration validation"],
    dispatchCount: 3,
    completedDispatchCount: 1,
    artifactCount: 1,
    updatedAt: "2026-03-25 19:48",
  },
]);

export const activityFeed = missionTimelineEventSchema.array().parse([
  {
    id: "evt-1",
    title: "Mission contracts synchronized",
    detail: "Shared contract layer now aligns mission, dispatch, QA, and artifact schemas.",
    actor: "Commander",
    at: "2026-03-25 21:10",
    status: "approved",
  },
  {
    id: "evt-2",
    title: "Dispatch handoff submitted",
    detail: "Executor delivered UI framework components for dashboard assembly.",
    actor: "Executor",
    at: "2026-03-25 21:24",
    status: "submitted",
  },
  {
    id: "evt-3",
    title: "QA review queued",
    detail: "Page layer can now consume typed cards and rows without extra UI glue.",
    actor: "QA Operator",
    at: "2026-03-25 21:32",
    status: "qa_review",
  },
  {
    id: "evt-4",
    title: "Seed layer centralized",
    detail: "Part 8 moved mock records into src/lib/seed for easier future replacement.",
    actor: "Integrator",
    at: "2026-03-26 00:05",
    status: "ready",
  },
]);
