import { artifactSchema } from "@/lib/contracts/artifact";

export const artifactsMock = artifactSchema.array().parse([
  {
    id: "art-1",
    missionId: "mis-001",
    dispatchId: "dis-101",
    title: "Mission card component",
    description: "Reusable presentation card for mission summaries.",
    kind: "ui",
    status: "approved",
    owner: "Frontend Operator",
    updatedAt: "2026-03-25 21:18",
    path: "src/components/missions/mission-card.tsx",
    sizeLabel: "2.1 KB",
    tags: ["component", "mission"],
  },
  {
    id: "art-2",
    missionId: "mis-002",
    dispatchId: "dis-103",
    title: "Dashboard UI notes",
    description: "Notes for page-layer integration and reuse points.",
    kind: "report",
    status: "review",
    owner: "QA Operator",
    updatedAt: "2026-03-25 21:34",
    path: "src/docs/dashboard-ui-framework-notes.md",
    sizeLabel: "1.4 KB",
    tags: ["docs", "handoff"],
  },
  {
    id: "art-3",
    missionId: "mis-003",
    dispatchId: "dis-104",
    title: "Centralized seed bundle",
    description: "Unified seed layer for missions, dispatches, QA, and artifacts.",
    kind: "bundle",
    status: "generated",
    owner: "Integrator",
    updatedAt: "2026-03-26 00:05",
    path: "src/lib/seed/index.ts",
    sizeLabel: "3.8 KB",
    tags: ["seed", "integration"],
  },
]);
