import { dispatchSchema } from "@/lib/contracts/dispatch";

export const dispatchesMock = dispatchSchema.array().parse([
  {
    id: "dis-101",
    missionId: "mis-001",
    title: "Build mission summary card",
    summary: "Typed card with progress, status, owner, blockers, and tags.",
    assignee: "Frontend Operator",
    status: "approved",
    domain: "dashboard_framework",
    scope: ["src/components/missions/mission-card.tsx"],
    dependencies: [],
    attemptCount: 1,
    updatedAt: "2026-03-25 21:19",
    outputSummary: "Card finalized and ready for page composition.",
  },
  {
    id: "dis-102",
    missionId: "mis-001",
    title: "Build dispatch row",
    summary: "Queue-ready row with assignee, dependencies, attempts, and scope chips.",
    assignee: "Frontend Operator",
    status: "working",
    domain: "dashboard_framework",
    scope: ["src/components/dispatches/dispatch-row.tsx"],
    dependencies: ["dis-101"],
    attemptCount: 2,
    updatedAt: "2026-03-25 21:31",
    dueAt: "2026-03-25 22:00",
  },
  {
    id: "dis-103",
    missionId: "mis-002",
    title: "Prepare QA review card",
    summary: "Review surface for checklists, evidence, decision, and blockers.",
    assignee: "QA Operator",
    status: "qa_review",
    domain: "qa",
    scope: ["src/components/qa/qa-review-card.tsx"],
    dependencies: [],
    attemptCount: 1,
    updatedAt: "2026-03-25 21:28",
  },
  {
    id: "dis-104",
    missionId: "mis-003",
    title: "Centralize mock data",
    summary: "Move page-local mock data into lib/seed and preserve typed contracts.",
    assignee: "Integrator",
    status: "ready",
    domain: "integration_docs",
    scope: [
      "src/lib/seed/mock-missions.ts",
      "src/lib/seed/mock-dispatches.ts",
      "src/lib/seed/mock-qa.ts",
      "src/lib/seed/mock-artifacts.ts",
    ],
    dependencies: ["dis-101", "dis-103"],
    attemptCount: 1,
    updatedAt: "2026-03-25 23:58",
  },
  {
    id: "dis-105",
    missionId: "mis-004",
    title: "Validate blocked transition rules",
    summary: "Check that blocked missions can re-enter ready or in-progress safely.",
    assignee: "Systems Operator",
    status: "blocked",
    domain: "mission_state",
    scope: ["src/lib/state/mission-state-machine.ts"],
    dependencies: [],
    attemptCount: 3,
    updatedAt: "2026-03-25 19:48",
    outputSummary: "Waiting for integration-level confirmation.",
  },
]);
